[package]
name = "spread_spectrum_watermarking"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"


[dependencies]
image = "0.24.3"
rustdct = "0.7.0"
rand = "0.8.5"
rand_distr = "0.4.3"

[dev-dependencies]
rand_xoshiro = "0.6.0"
