[package]
name = "spread_spectrum_watermarking"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"


[dependencies]
image = "0.24.3"
rustdct = "0.7.0"

#https://doc.rust-lang.org/cargo/reference/features.html#dependency-features
